//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNotificationNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPNaqelEntitiesLive : DbContext
    {
        public ERPNaqelEntitiesLive()
            : base("name=ERPNaqelEntitiesLive")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmailNotificationLog> EmailNotificationLogs { get; set; }
        public virtual DbSet<EmailNotificationPickup> EmailNotificationPickups { get; set; }
        public virtual DbSet<OFDEmailNotificationLog> OFDEmailNotificationLogs { get; set; }
        public virtual DbSet<ViwEmailNotificationDelivered> ViwEmailNotificationDelivereds { get; set; }
        public virtual DbSet<ViwEmailNotificationOFD> ViwEmailNotificationOFDs { get; set; }
        public virtual DbSet<SMSSentMessage> SMSSentMessages { get; set; }
        public virtual DbSet<ViwRateCheck> ViwRateChecks { get; set; }
        public virtual DbSet<ComplaintNotification> ComplaintNotifications { get; set; }
        public virtual DbSet<ViwComplaintNotification> ViwComplaintNotifications { get; set; }
    }
}
