//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNotificationNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFDEmailNotificationLog
    {
        public int ID { get; set; }
        public Nullable<int> WaybillNo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsOFD_EmailSent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<bool> IsExceptions_EmailSent { get; set; }
    }
}
