//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNotificationNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSentMessage
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string RefNo { get; set; }
        public string MobileNo { get; set; }
        public string Message { get; set; }
        public int EmployID { get; set; }
        public int SMSSendingStatusID { get; set; }
        public int PurposeID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public string Balance { get; set; }
        public Nullable<bool> IsWhatsApp { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<bool> IsCNEEConfirmed { get; set; }
        public string CoreText { get; set; }
        public Nullable<bool> IsSyncToMySQL { get; set; }
        public Nullable<int> AccountNo { get; set; }
        public Nullable<int> UnitCount { get; set; }
        public string ResponseMessageID { get; set; }
        public Nullable<bool> IsNotificationPushed { get; set; }
    }
}
