//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNotificationNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViwComplaintClosedchatbot
    {
        public int ID { get; set; }
        public int ComplaintStatusID { get; set; }
        public Nullable<int> ComplaintSourceID { get; set; }
        public string ClosedDescription { get; set; }
        public string ComplaintDetails { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
        public string EmailID { get; set; }
    }
}
