//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNotificationNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViwComplaintNotification
    {
        public int Id { get; set; }
        public Nullable<int> ComplaintID { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsOpenEmailSent { get; set; }
        public Nullable<bool> IsClosedEmailSent { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Name { get; set; }
        public string ClosedDescription { get; set; }
    }
}
