//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNotificationNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViwEmailNotificationException
    {
        public int waybillno { get; set; }
        public string CneeEmail { get; set; }
        public string CneeName { get; set; }
        public string ShipperNameEN { get; set; }
        public string ShipperNameAR { get; set; }
    }
}
