//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNotificationNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViwRateCheck
    {
        public int ID { get; set; }
        public int WayBillNo { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<int> EmployID { get; set; }
        public string Balance { get; set; }
    }
}
