//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailNotificationNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waybill
    {
        public int ID { get; set; }
        public int WayBillNo { get; set; }
        public int ClientID { get; set; }
        public int ClientAddressID { get; set; }
        public int ClientContactID { get; set; }
        public int ServiceTypeID { get; set; }
        public int LoadTypeID { get; set; }
        public int BillingTypeID { get; set; }
        public int ConsigneeID { get; set; }
        public int ConsigneeAddressID { get; set; }
        public int OriginStationID { get; set; }
        public int DestinationStationID { get; set; }
        public System.DateTime PickUpDate { get; set; }
        public double PicesCount { get; set; }
        public double Weight { get; set; }
        public double Width { get; set; }
        public double Length { get; set; }
        public double Height { get; set; }
        public double VolumeWeight { get; set; }
        public Nullable<int> TripCodeID { get; set; }
        public bool IsInsurance { get; set; }
        public double ServiceCharge { get; set; }
        public Nullable<double> HandlingCharge { get; set; }
        public double PackingCharge { get; set; }
        public double StorageCharge { get; set; }
        public double DeclaredValue { get; set; }
        public double InsuredValue { get; set; }
        public double InsuranceCharge { get; set; }
        public double SpecialCharge { get; set; }
        public double OtherCharge { get; set; }
        public double TotalCharge { get; set; }
        public double Discount { get; set; }
        public string DiscountType { get; set; }
        public double NetCharge { get; set; }
        public double PaidAmount { get; set; }
        public int InvoiceAccount { get; set; }
        public Nullable<int> InvoiceAccountSl { get; set; }
        public double OnAccount { get; set; }
        public string PlateNo { get; set; }
        public string Remarks { get; set; }
        public string Contents { get; set; }
        public int RouteID { get; set; }
        public bool IsEmergency { get; set; }
        public int PickUpBy { get; set; }
        public bool PODNeeded { get; set; }
        public string PODDetail { get; set; }
        public string DeliveryInstruction { get; set; }
        public bool IsDelivered { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public bool IsCancelled { get; set; }
        public string CancelledReason { get; set; }
        public string WaybillContact { get; set; }
        public Nullable<int> TruckType { get; set; }
        public Nullable<int> DropPoints { get; set; }
        public double DropCharge { get; set; }
        public bool Invoiced { get; set; }
        public Nullable<bool> PODNeeded2 { get; set; }
        public string ConsigneeAttention { get; set; }
        public string BookingRefNo { get; set; }
        public Nullable<int> PODTypeID { get; set; }
        public double ODAStationCharge { get; set; }
        public Nullable<int> ODAStationID { get; set; }
        public Nullable<double> StandardShipment { get; set; }
        public Nullable<int> StandardTariffID { get; set; }
        public Nullable<int> AgreementID { get; set; }
        public Nullable<int> InsPercentage { get; set; }
        public Nullable<int> DRouteID { get; set; }
        public Nullable<bool> IsServiceManual { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public Nullable<int> detail_serial { get; set; }
        public Nullable<int> invc_account_sl { get; set; }
        public Nullable<int> consignee_serial { get; set; }
        public Nullable<bool> IsServiceChargeUpdate { get; set; }
        public Nullable<int> DeliveryBy { get; set; }
        public Nullable<System.DateTime> ManifestedTime { get; set; }
        public Nullable<int> SalesManID { get; set; }
        public string RefNo { get; set; }
        public string LastEvent { get; set; }
        public Nullable<double> TotalGCCCharges { get; set; }
        public Nullable<System.DateTime> LastEventTime { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<double> ODADStationCharge { get; set; }
        public Nullable<int> ODADStationID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> TransitTimeDays { get; set; }
        public Nullable<bool> IsRTO { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> OldWaybillNo { get; set; }
        public Nullable<bool> IsMultiDimension { get; set; }
        public Nullable<double> CollectedAmount { get; set; }
        public Nullable<double> AmountForClient { get; set; }
        public Nullable<bool> IsSyncAx { get; set; }
        public Nullable<double> CustomDuty { get; set; }
        public Nullable<int> BandDiscountID { get; set; }
        public Nullable<int> DestClientBranchID { get; set; }
        public Nullable<int> OrgClientBranchID { get; set; }
        public Nullable<int> DeliveryTruckID { get; set; }
        public Nullable<int> PickUpPiecesCount { get; set; }
        public Nullable<bool> IsSMSSent { get; set; }
        public Nullable<System.DateTime> TimSendingSMS { get; set; }
        public Nullable<int> SMSSendingStatusID { get; set; }
        public string IQamaFilePath { get; set; }
        public string IQamaNo { get; set; }
        public Nullable<double> FuelSurchargePercentage { get; set; }
        public Nullable<double> FuelSurchargeAmount { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<int> TrackingID { get; set; }
        public Nullable<int> LastEventID { get; set; }
        public Nullable<int> RTOID { get; set; }
        public Nullable<int> PINCode { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> DeclaredValueCurrencyID { get; set; }
        public string GoodDesc { get; set; }
        public Nullable<int> FromCountryID { get; set; }
        public Nullable<int> ToCountryID { get; set; }
        public Nullable<int> CourierSupplierID { get; set; }
        public Nullable<double> PackingChargeAmount { get; set; }
        public Nullable<bool> HasPackingService { get; set; }
        public Nullable<double> CBM { get; set; }
        public string FinanceComment { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> HoldNoInvoice { get; set; }
        public Nullable<int> HoldBy { get; set; }
        public Nullable<double> VATPercentage { get; set; }
        public Nullable<double> VATAmount { get; set; }
        public Nullable<double> CustomClearance { get; set; }
        public Nullable<int> GiftVoucherID { get; set; }
        public Nullable<double> CustomClearanceVAT { get; set; }
        public string PointerRoute { get; set; }
        public Nullable<double> ConsigneeCustomDuty { get; set; }
        public Nullable<double> ConsigneeCustomClearanceVAT { get; set; }
        public Nullable<bool> IsPayedByConsignee { get; set; }
        public Nullable<bool> IsHighValue { get; set; }
        public Nullable<int> SubLoadTypeID { get; set; }
        public Nullable<int> TemperatureID { get; set; }
        public string ActualTemperature { get; set; }
        public Nullable<bool> ServiceChargeInvoiced { get; set; }
        public Nullable<System.DateTime> DeliveryEntryDate { get; set; }
        public Nullable<double> TotalFFCharges { get; set; }
        public Nullable<double> ServiceSurCharge { get; set; }
        public Nullable<bool> addressChanged { get; set; }
        public Nullable<int> OriginFacilityID { get; set; }
        public Nullable<int> DestinationFacilityID { get; set; }
        public Nullable<double> PostalCharges { get; set; }
        public Nullable<int> OriginCityID { get; set; }
        public Nullable<int> DestinationCityID { get; set; }
        public Nullable<double> TransCurExchRate { get; set; }
        public Nullable<int> ReportCurrencyID { get; set; }
        public Nullable<int> ReportCurrencyExchangeRate { get; set; }
        public Nullable<int> AccountCurrencyID { get; set; }
        public Nullable<int> AccountExchangeRate { get; set; }
        public Nullable<double> ConsigHandlingFee { get; set; }
        public Nullable<double> ConsigHandlingFeeVATAmount { get; set; }
        public Nullable<double> ConsigHandlingFeeVATPercentage { get; set; }
        public Nullable<int> ConsigneeBillTypeID { get; set; }
    }
}
